"""
This module handles the widget to access the cropped images generated by the
gallery widget and display them in a gui application for training
"""


# Logging

import logging
from omero_screen_napari.omero_data_singleton import omero_data
from magicgui import magic_factory
from magicgui.widgets import Container
import napari


def training_widget():
    loading_instance = load_image()
    return Container(widgets=[loading_instance])


@magic_factory(
    call_button="Load Images",
)
def load_image():
    viewer = napari.current_viewer()
    cropped_images = omero_data.cropped_images
    if not cropped_images:
        print("No images to load.")
        return
    viewer.layers.clear()  # Clear all existing layers
    viewer.add_image(cropped_images[0], name='Cropped Image 0')

